### ISSUE TITLE
Facing issues while running it

### ISSUE THREAD

**Issue by theshivamsk** [AlexandreSajus/JARVIS#11]
--> Getting this while running main.py

[Running] python -u "c:\Users\LENOVO\JARVIS\main.py"
pygame 2.5.2 (SDL 2.28.3, Python 3.12.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:\Users\LENOVO\JARVIS\main.py", line 15, in <module>
    from record import speech_to_text
  File "c:\Users\LENOVO\JARVIS\record.py", line 8, in <module>
    from rhasspysilence import WebRtcVadRecorder, VoiceCommand, VoiceCommandResult
ModuleNotFoundError: No module named 'rhasspysilence'

=========================

--> I'm getting this while running display.py

[Running] python -u "c:\Users\LENOVO\JARVIS\display.py"
Traceback (most recent call last):
  File "c:\Users\LENOVO\JARVIS\display.py", line 13, in <module>
    def on_init(state: State) -> None:
                       ^^^^^
NameError: name 'State' is not defined

**Comment by AlexandreSajus** [comment]
The Taipy version I am using here is old, I really need to update the project at some point since I have been getting a lot of issues with this. Basically the project needs Python 3.8 to 3.11 to run so just switch to these versions of Python. You can also try updating taipy, our latest version supports Python 3.12

As for rhasspysilence, try this: https://github.com/AlexandreSajus/JARVIS/issues/4

Let me know if this works out
